name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 16 ] 
        
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }} for build
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn -V --file pom.xml --no-transfer-progress clean package

  deploy:

    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - name: Set up JDK ${{ matrix.java }} for deploy
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: ossrh
        server-username: NEXUS_USERNAME # env variable for username in deploy
        server-password: NEXUS_PASSWORD # env variable for token in deploy
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish to Nexus OSS
      run: mvn deploy
      env:
        NEXUS_USERNAME: xerprojects
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}