name: Dev Deploy

on:
  workflow_run:
    workflows: ["Maven Build"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/cache@v2.1.5
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK ${{ matrix.java }} for deploy
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        server-id: ossrh
        server-username: NEXUS_USERNAME # env variable for username in deploy
        server-password: NEXUS_PASSWORD # env variable for token in deploy
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish SNAPSHOT to ossrh
      # Enable release profile
      run: mvn -V --file pom.xml --no-transfer-progress -Psnapshots,release -U clean deploy
      env:
        NEXUS_USERNAME: xerprojects
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}